### PR TITLE
Improve type definition of `Mocker.__call__`

### PR DESCRIPTION
**Pull request by Viicos**
- Use new style syntax (see https://typing.readthedocs.io/en/latest/source/stubs.html, as it is now supported by all type checkers, it is safe)
- Improve typing of `Mocker.__call__`, with basic support [^1]
- Format stubs with black (which handles `.pyi` files in a special way).

[^1]: [`ParamSpec`](https://docs.python.org/3/library/typing.html#typing.ParamSpec) and [`Concatenate`](https://docs.python.org/3/library/typing.html#typing.Concatenate) can't be used to add the `m` parameter (for two reasons: there's no way to concatenate to kwargs, and even if `kw` is not set on the `Mocker` instance, concatenating a posarg is only possible if it is added first (i.e. `Concatenate[P, Mocker]` is not possible))

### CODE REVIEW

**Comment by jamielennox** [comment]
Responding to comment. I looked this over, there's a few bits I just need to figure out: 

- how much of the changes are real, and how much is black being black? Like replacing `Optional[]` with `| None`, is that an actual change that I need to research? (In general I don't care about black, but if it matters I'd do it as a separate pr so we can say there are no actual changes here).

- I was going to look through which version introduced some of the syntax. I guess going forward I'm looking to support only the supported options like everyone else, but I just wanted to say least check it.

- Given the drop of python 2, the need to maintain the types in the their own .pyi files has largely gone away. There's no real ROI I'm aware of that makes it an urgent process, but I was going to check how it looked after #248..



Anyway, that's my very late night rambling to do list, but it's probably fine. Still if there's a real functional change in their that you're waiting on I'd just submit that as something contained and reviewable on its own. That's a lot easier to review than something that rewrites a lot of syntax for no obvious benefit.

**Comment by Viicos** [comment]
Yes sorry would have probably been easier in separate commits.

> how much of the changes are real, and how much is black being black?

The only functional change can be looked up [here](https://github.com/jamielennox/requests-mock/pull/244/files#diff-a9acca4e7d0a1ec4cdb7804b1e3369a80aa21f5ce67d3fb89d983f6ae004a22dR250-R253).

> Still if there's a real functional change in their that you're waiting on I'd just submit that as something contained and reviewable on its own. That's a lot easier to review than something that rewrites a lot of syntax for no obvious benefit.

Do you want me to make a separate PR for it?

> I was going to look through which version introduced some of the syntax. I guess going forward I'm looking to support only the supported options like everyone else, but I just wanted to say least check it.

When writing stub files, you can usually make use of new typing features (in this case, the new union style syntax and builtins supporting subscripting: `typing.List[int]` -> `list[int]`) as soon as they are supported by the major type checkers, not when the Python version introducing this features is the last one being supported.

> Given the drop of python 2, the need to maintain the types in the their own .pyi files has largely gone away. 

It could be merged back into the source files indeed. However, the library seems to be doing a lot of magic, so it might be tricky in some places (whereas type stubs can express anything, even if it's not written the same way in the source). I'll investigate on that, and could make a PR with the types merged back if you are open to it (as it might take some review effort)

**Comment by jamielennox** [comment]
Yea, please extract the functional bit, that looks pretty trivial and i can just merge it straight away.

For the rest, sure, but it'll just kind of be on the todo list as i don't see a user impact that has any urgency.

**Comment by jamielennox** [comment]
I've merged all the python2 removal code. If you rebase it now the tests should work.

**Review by jamielennox — APPROVED** [review]

**Pull request merged**
