### PR TITLE
Move tests outside of package to top level directory

### PR DESCRIPTION
**Pull request by jamielennox**
Cleanly separates tests from the package itself. Prevents the tests
being installed to site-packages.Tests are still distributed with the
source distribution.

Change-Id: I2dc75d006b0f1eec2f6123b624ade4991a2704e8

### CODE REVIEW

**Comment by jamielennox** [comment]
Moved from https://review.openstack.org/#/c/521390/

**Comment by jamielennox** [comment]
Discussion from gerrit: 

## Jamie Lennox - Dec 5 10:03 AM

So this one is a matter of taste and something i believe is standard in the openstack community (which shouldn't be a definer of this project, but just what i'm familiar with).

Beyond pypi, changing this would require updates in all the downstream rpms and debs and so i'm not willing to change it without some form of best practice statement from either the python or openstack communities. 

Appreciate the thought though and let me know if this statement exists.

## jond - Dec 6 3:41 PM

> changing this would require updates in all the downstream rpms and debs

Would this be resolved by including the tests/ directory in the sdist through MANIFEST.in? For example, the command "graft tests"?

See https://docs.python.org/3/distutils/commandref.html for a description of what this would do.

## jond - Dec 6 3:49 PM

Patch Set 1:

RE: tests/ location best practices

I found the following article: 

http://docs.python-guide.org/en/latest/writing/structure/

This article recommends moving tests to the top level directory.  It has the blurb:

> Some people will assert that you should distribute your tests within your module itself – I disagree. It often increases complexity for your users; many test suites often require additional dependencies and runtime contexts.

It is also my observation that a very large number of big Python projects keep their tests at the top level. Of the many requirements I install for my project, requests-mock is the only one to install tests to site-packages. It is noticing this that prompted me to suggest the change.

Thanks for your time.

**Comment by jdufresne** [comment]
If you're still interested, I'd like to rebase this work to resolve merge conflicts. Should I open a new PR? I can't push to this repo.

**Comment by jdufresne** [comment]
I create #40 so I'd be able to edit the PR. You can close this one. I'll apply any changes through feedback there. Thanks!

**Comment by jamielennox** [comment]
@jdufresne Sorry, should have looked to see if I could grant you write permissions or something to the branch.

Closed in favour of #40

**Pull request closed without merging**
